--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RassyaYa/PEWings
build-by-default: true
branches:
- master
projects:
    PEWings:
    path: ""
    libs:
    - src: https://poggit.pmmp.io/ci/Infernus101/FormAPI/libFormAPI
...